server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/test_cems
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.ocean.pojo
