package com.vrv.cems.dao;

import com.vrv.cems.pojo.CemsUser;

import java.util.List;

public interface CemsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cems_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cems_user
     *
     * @mbggenerated
     */
    int insert(CemsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cems_user
     *
     * @mbggenerated
     */
    int insertSelective(CemsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cems_user
     *
     * @mbggenerated
     */
    CemsUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cems_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CemsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cems_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CemsUser record);


    List findAllUser();

}